### ISSUE TITLE
border-radius on indeterminate #progressContainer problematic

### ISSUE THREAD

**Issue by danbeam** [PolymerElements/paper-progress#15]
A `border-radius` on `#progressContainer` doesn't work for indeterminate progress bars (probably because of the [3D transforms in the @keyframes used to implement it](https://github.com/PolymerElements/paper-progress/blob/master/paper-progress.html#L150-L212)?)

Ex: http://imgur.com/a/7P0Jr (just hacked up paper-progress demo page)

/cc @frankiefu @blasten

**Comment by blasten** [comment]
@danbeam that's right. you will also need to style `#indeterminateSplitter` but this element doesn't expose a mixin. Also, the material design spec doesn't seem to include rounded corners.

**Comment by danbeam** [comment]
fwiw: there's no longer rounded corners for `<paper-progress>` bars in our mocks

this will probably still be hit by other devs, though.  spotify, for instance, has a progress bar that [looks just like `<paper-progress>` with rounded corners](http://i.imgur.com/ifhz0Vu.png).

**Comment by blasten** [comment]
Iron elements are the building blocks for paper elements. e.g. iron-range-behavior https://github.com/PolymerElements/iron-range-behavior

Paper elements try to be as flexible as possible while respecting the material design spec. One can use iron-elements to create different progress bars, e.g.  `<spotify-progress>`

Good to know that the design doesn't need rounded corners, I'm closing this issue then.
