### ISSUE TITLE
paper-progress event

### ISSUE THREAD

**Issue by ghost** [PolymerElements/paper-progress#36]
Hi there,

Is there any event fired when sliding the paper-progress ?
I've tried on-iron-change but it does not work.

Thanks

**Comment by keanulee** [comment]
`<paper-progress>` is a progress bar, so as a developer you are updating its value (and should know when it changes). Did you mean `<paper-slider>` (in which case you can listen for `immediate-value-change`)?

**Comment by ghost** [comment]
Oh, yeah i did not see that element .. I'm sorry.
Thanks !
