### ISSUE TITLE
linear gradient

### ISSUE THREAD

**Issue by nanu-c** [PolymerElements/paper-progress#39]
is it possible that this could work?

```
    paper-progress {
      --paper-progress-active-color: linear-gradient(to right, #1e5799 0%,#2989d8 10%,#207cca 35%,#f96800 55%,#af0000 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
    }
```

**Comment by keanulee** [comment]
That would require changes the `paper-progress` but shouldn't be too hard to implement (just change the custom property to be applied to `background` instead of `background-color`). Mind sending a pull request?
