### ISSUE TITLE
Add a `start` attribute to position the progress bar

### ISSUE THREAD

**Issue by jarrodek** [PolymerElements/paper-progress#44]
### Description

The `paper-progress` element could be using a `start` property to position the bar in Y axis. This can be useful to build timelines like grant charts.
### Expected outcome

After setting this attribute the bar is moved to the right by corresponding position relative to the value.

I've prepared a PR for that. It's on its way.

**Comment by keanulee** [comment]
Closed - see https://github.com/PolymerElements/paper-progress/pull/45#issuecomment-215237251
