### ISSUE TITLE
paper-progress disappears in zoomed out views

### ISSUE THREAD

**Issue by stevenjb** [PolymerElements/paper-progress#57]
### Description
When zooming out on a page on a non high DPI display (e.g. to 33%) using a Chrome browser, the progress bar in a paper slider appears to disappear.

### Expected outcome

The progress bar should not disappear.

A potential fix would be to use a border instead. See discussion here:
PolymerElements/paper-input#448

### Actual outcome

Sometimes the progress bar disappears. At 25% it is more likely to disappear.

### Live Demo
This can be seen in chrome settings or the paper-slider demo page:
chrome://md-settings/fonts
https://elements.polymer-project.org/bower_components/paper-slider/demo

### Steps to reproduce

Visit a page with a paper-slider and use ctrl+shift+- (Or Zoom - in the Chrome dropdown menu) to zoom out.

### Browsers Affected

- [x ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by danbeam** [comment]
@frankiefu @keanulee if we use a `border` instead of an element `height`, this Just Works :tm:

example that I did for paper-input: https://github.com/PolymerElements/paper-input/pull/455

**Comment by danbeam** [comment]
note, that because `<paper-slider>` is implemented with a `<paper-progress>`, this would fix 2 elements for the price of 1 :smile:

**Comment by keanulee** [comment]
Due to the fact that this would be a breaking change, we will not be fixing this. Feel free to examine the code in #64 and create your own slider if this functionality is desired.
