### ISSUE TITLE
secondary progress is not always visible when using indeterminate

### ISSUE THREAD

**Issue by araker** [PolymerElements/paper-progress#68]
### Description
Insert a progress element with the following syntax 
` <paper-progress indeterminate class="blue" secondary-progress="80"></paper-progress>`

### Expected outcome
I expect that the secondary progress is always visible, independent of the foreground animation

### Actual outcome
Every other cycle the foreground animation let the secondary progress bar disappear.

### Live Demo
Edit the demo (https://www.webcomponents.org/element/PolymerElements/paper-progress/demo/demo/index.html) with the line from the description

### Steps to reproduce
See live demo

### Browsers Affected

- [x ] Chrome
others not tested

**Comment by keanulee** [comment]
That's because we use another element (with the same background color as the container) to overlay the primary progress to create that animation. In other words, using secondary progress with indeterminate is not supported.
