### ISSUE TITLE
paper-progress accessibility issues - Firefox specific 

### ISSUE THREAD

**Issue by lpalmaro** [PolymerElements/paper-progress#7]
For the most part this is fine. It's not really an interactive element, so keyboard navigation doesn't really apply here. That said, I wanted to take a quick look with how the screen readers function on the progress bars to report progress to the user.

On Firefox with NVDA, it's not possible to access the bars to hear progress. This is not the case on Chrome across platforms, or Safari though.

**Comment by blasten** [comment]
`paper-progress` has a `aria-valuenow` attribute  and a `role=progressbar` which should indicate the current value of the progress to NVDA.  Ref:

[1] https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Web_applications_and_ARIA_FAQ
[2] https://github.com/PolymerElements/paper-progress/blob/master/paper-progress.html#L120

I could review the firefox case again, but it seems like it's already doing what is documented in `[1]`.
