### ISSUE TITLE
class styling is not working

### ISSUE THREAD

**Issue by hedcet** [PolymerElements/paper-progress#81]
currently, i have multiple progress-bar in one page & i need to give different color for each one
so i tried css path with class like ```paper-progress.<classname>```

```
paper-progress.1 {
  --paper-progress-active-color: #C23531;
  --paper-progress-secondary-color: rgb(194, 53, 49, .3);
 }
```
its not working, pls support css path with class
i know the same thing with this format ```paper-progress[class="1"]``` will work

**Comment by keanulee** [comment]
`1` is not a valid CSS class name - class names must not start with a number https://stackoverflow.com/questions/448981/which-characters-are-valid-in-css-class-names-selectors
